/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "log.h"

bool_t
log_operation_1_svc(char *user, char *operation, char *filename, int *result,  struct svc_req *rqstp)
{
	bool_t retval = TRUE;

	printf("l> %s   %s %s\n", user, operation, filename );
	*result = 1;

	return retval;
}

int
log_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
