
# This is a template Makefile generated by rpcgen

# Parameters

CLIENT = log_client
SERVER = log_server

SOURCES_CLNT.c = 
SOURCES_CLNT.h = 
SOURCES_SVC.c = 
SOURCES_SVC.h = 
SOURCES.x = log.x

TARGETS_SVC.c = log_svc.c log_server.c log_xdr.c 
TARGETS_CLNT.c = log_clnt.c log_client.c log_xdr.c 
TARGETS = log.h log_xdr.c log_clnt.c log_svc.c log_client.c log_server.c

OBJECTS_CLNT = $(SOURCES_CLNT.c:%.c=%.o) $(TARGETS_CLNT.c:%.c=%.o)
OBJECTS_SVC = $(SOURCES_SVC.c:%.c=%.o) $(TARGETS_SVC.c:%.c=%.o)
# Compiler flags 

CPPFLAGS += -D_REENTRANT
CFLAGS += -g 
LDLIBS += -lnsl -lpthread 
 RPCGENFLAGS = -NM

# Targets 

all : server $(CLIENT) $(SERVER)

$(TARGETS) : $(SOURCES.x) 
	rpcgen $(RPCGENFLAGS) $(SOURCES.x)

$(OBJECTS_CLNT) : $(SOURCES_CLNT.c) $(SOURCES_CLNT.h) $(TARGETS_CLNT.c) 

$(OBJECTS_SVC) : $(SOURCES_SVC.c) $(SOURCES_SVC.h) $(TARGETS_SVC.c) 

$(CLIENT) : $(OBJECTS_CLNT) 
	$(LINK.c) -o $(CLIENT) $(OBJECTS_CLNT) $(LDLIBS) 

$(SERVER) : $(OBJECTS_SVC) 
	$(LINK.c) -o $(SERVER) $(OBJECTS_SVC) $(LDLIBS)

server : server.c server.h db.c db.h log.h
	gcc server.c db.c log_clnt.c log_xdr.c -o server -lpthread -lnsl

 clean:
	 $(RM) core log.h log_xdr.c log_clnt.c log_svc.c $(OBJECTS_CLNT) $(OBJECTS_SVC) $(CLIENT) $(SERVER) server